# Generated by Django 5.0.6 on 2024-05-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='price_unit',
            field=models.CharField(blank=True, choices=[('ea', 'Each'), ('lb', 'Pound'), ('ct', 'Count')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('ea', 'Each'), ('lb', 'Pound'), ('ct', 'Count')], max_length=10, null=True),
        ),
    ]
